MERGE INTO dbo.RUSIACODE_TEST AS target
USING #Temp AS source
ON target.RUSIACODE_CODE = source.RUSIACODE_CODE
WHEN MATCHED AND ISNULL(target.COL2, '') <> ISNULL(source.COL2, '')
THEN
    UPDATE SET target.COL2 = source.COL2
WHEN NOT MATCHED THEN
    INSERT (RUSIACODE_CODE, COL2)
    VALUES (source.RUSIACODE_CODE, source.COL2);
